### ISSUE TITLE
Imperative Matlab: Nixos Wiki

### ISSUE THREAD

**Issue by Mazurel** [tviti/nix-cfg#2]
Hello, 
I would like to write on NixOS Wiki about using Matlab on NixOS. This post would strongly base on your work and I wanted to ask if it is ok for you. I would put links to your repo and give you full credit for your work.

By the way thanks a lot for your work, you have really managed to do something great as only with slight modifications Matlab R2021a works with no problem even with Simulink !

**Comment by tviti** [comment]
Yes, that's absolutely OK with me! There were a few moments setting this up where I started to question the value of spending this much effort getting this to work, so I'd be really happy to see ideas from this repo helping others to make NixOS amenable to their workflows.

Note: The aunuu branch is the one that I use for my daily driver, so you might want to base any writing off of that one.

You might also want also want to checkout https://github.com/tviti/nix-cfg/issues/1#issuecomment-841659924 since it souonds like @doronbehar has [an interesting project](https://gitlab.com/doronbehar/nix-matlab) that's based off of this one (although if I'm being honest, I'm not entirely sure what it does).

**Comment by Mazurel** [comment]
Thanks a lot for the response, I have seen @doronbehar work, although it is oriented around flakes and sadly my configuration is not using flakes yet.

**Comment by doronbehar** [comment]
> although it is oriented around flakes and sadly my configuration is not using flakes yet.

@Mazurel I tried to set up my project in a way that will be non flakes compatible, did you try to give it a try? For instance:

https://gitlab.com/doronbehar/nix-matlab#user-content-for-nixos-users-without-a-flakes-setup

I'd be happy to get comments and suggestions to the README suitable for non flakes users.

**Comment by Mazurel** [comment]
Yeah, I feel kind of ashamed now as somehow I have not seen that you have made an entry for non flakes users. I will give it definitely a look later and give you some feedback.
